""" 
Algoritmo principal. Aca es donde esta la ejecucion paso a paso de las problematicas detalladas
"""
#! PRIMERO SE IMPORTAN LAS CONSTANTES
from ... import ...
#! DESPUES SE IMPORTAN LAS CLASES
...
#! DESPUES SE IMPORTAN LAS FUNCIONES
...

if __name__ == '__main__':
        #! PRIMERA PROBLEMATICA
        #! ...
        #! ...

        #! SEGUNDA PROBLEMATICA
        #! ...
        #! ...
        pass